# Generated by Django 5.2.14 on 2026-05-14 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'dim_categorie',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('code_client', models.CharField(max_length=50, unique=True)),
                ('nom_client', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('recence', models.IntegerField(default=0)),
                ('frequence', models.IntegerField(default=0)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('segment_rfm', models.CharField(choices=[('champions', 'Champions'), ('clients_fideles', 'Clients Fidèles'), ('clients_potentiels', 'Clients Potentiels'), ('nouveaux', 'Nouveaux Clients'), ('clients_perdus', 'Clients Perdus'), ('hibernation', 'En Hibernation')], default='nouveaux', max_length=20)),
                ('score_rfm', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'dim_client',
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id_commercial', models.AutoField(primary_key=True, serialize=False)),
                ('code_commercial', models.CharField(max_length=50, unique=True)),
                ('nom_commercial', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
                'db_table': 'dim_commercial',
            },
        ),
        migrations.CreateModel(
            name='ConversationChatbot',
            fields=[
                ('id_conversation', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('user_message', models.TextField()),
                ('intent_detecte', models.CharField(blank=True, max_length=20, null=True)),
                ('confiance', models.FloatField(default=0)),
                ('reponse', models.TextField()),
                ('sql_genere', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversation Chatbot',
                'verbose_name_plural': 'Conversations Chatbot',
                'db_table': 'fact_conversation_chatbot',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DimensionAnalyse',
            fields=[
                ('id_dimension', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('champ_sql', models.CharField(help_text='Expression SQL ou champ modèle (ex: commande__client__region)', max_length=200)),
                ('table_source', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Dimension d'analyse",
                'verbose_name_plural': "Dimensions d'analyse",
                'db_table': 'config_dimension',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('cle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valeur', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre Système',
                'verbose_name_plural': 'Paramètres Système',
                'db_table': 'parametre_systeme',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('date_commande', models.DateField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='analytics.client')),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='analytics.commercial')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'fait_commande',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationProjet',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('nom_projet', models.CharField(default='Mon Dashboard', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('colonnes_canevas', models.JSONField(default=dict, help_text='Structure JSON des colonnes attendues: [{nom, type, obligatoire, description}]')),
                ('theme_couleur', models.CharField(default='#f97316', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration projet',
                'verbose_name_plural': 'Configurations projet',
                'db_table': 'config_projet',
            },
        ),
        migrations.CreateModel(
            name='DonneeBrute',
            fields=[
                ('id_donnee', models.AutoField(primary_key=True, serialize=False)),
                ('date_transaction', models.DateField()),
                ('code_client', models.CharField(max_length=50)),
                ('nom_client', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('code_article', models.CharField(max_length=50)),
                ('nom_article', models.CharField(blank=True, max_length=200)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('code_commercial', models.CharField(blank=True, max_length=50)),
                ('nom_commercial', models.CharField(blank=True, max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('champs_personnalises', models.JSONField(blank=True, default=dict)),
                ('ca_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('marge_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees', to='analytics.configurationprojet')),
            ],
            options={
                'verbose_name': 'Donnée brute',
                'verbose_name_plural': 'Données brutes',
                'db_table': 'donnee_brute',
            },
        ),
        migrations.CreateModel(
            name='IndicateurPersonnalise',
            fields=[
                ('id_indicateur', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_calcul', models.CharField(choices=[('somme', 'Somme'), ('moyenne', 'Moyenne'), ('compte', 'Compte distinct'), ('formule', 'Formule personnalisée'), ('ratio', 'Ratio entre 2 champs'), ('pourcentage', 'Pourcentage de variation'), ('min', 'Minimum'), ('max', 'Maximum')], default='somme', max_length=20)),
                ('type_affichage', models.CharField(choices=[('nombre', 'Nombre'), ('montant', 'Montant (DZD)'), ('pourcentage', 'Pourcentage'), ('duree', 'Durée (jours)'), ('texte', 'Texte')], default='montant', max_length=20)),
                ('champ_source', models.CharField(blank=True, help_text='Champ de la table source (ex: ca_ligne)', max_length=100)),
                ('table_source', models.CharField(default='fait_ligne_commande', max_length=100)),
                ('formule', models.TextField(blank=True, help_text='Formule SQL ou expression Python (si type=formule)')),
                ('champ_numerateur', models.CharField(blank=True, max_length=100)),
                ('champ_denominateur', models.CharField(blank=True, max_length=100)),
                ('seuil_alerte_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seuil_alerte_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('couleur_positive', models.CharField(default='#22c55e', max_length=7)),
                ('couleur_negative', models.CharField(default='#ef4444', max_length=7)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('icone', models.CharField(default='fa-chart-line', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicateur personnalisé',
                'verbose_name_plural': 'Indicateurs personnalisés',
                'db_table': 'config_indicateur',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='IntentChatbot',
            fields=[
                ('id_intent', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.TextField()),
                ('intent', models.CharField(choices=[('kpi_request', 'Demande de KPI'), ('comparison_request', 'Demande de comparaison'), ('trend_request', 'Demande de tendance'), ('anomaly_request', "Détection d'anomalie"), ('product_request', 'Info produit'), ('category_request', 'Info catégorie'), ('greeting', 'Salutation'), ('fallback', 'Fallback')], max_length=20)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intention Chatbot',
                'verbose_name_plural': 'Intentions Chatbot',
                'db_table': 'dim_intent_chatbot',
                'unique_together': {('phrase', 'intent')},
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('code_article', models.CharField(max_length=50, unique=True)),
                ('nom_article', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='analytics.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'dim_produit',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ca_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('marge_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='analytics.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='analytics.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'fait_ligne_commande',
            },
        ),
        migrations.CreateModel(
            name='SessionNavigation',
            fields=[
                ('id_session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_secondes', models.IntegerField(default=0)),
                ('source_trafic', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.client')),
            ],
            options={
                'verbose_name': 'Session de navigation',
                'verbose_name_plural': 'Sessions de navigation',
                'db_table': 'fact_session_navigation',
            },
        ),
        migrations.CreateModel(
            name='EvenementComportemental',
            fields=[
                ('id_evenement', models.AutoField(primary_key=True, serialize=False)),
                ('type_evenement', models.CharField(choices=[('vue_produit', 'Vue Produit'), ('ajout_panier', 'Ajout Panier'), ('abandon_panier', 'Abandon Panier'), ('achat', 'Achat'), ('recherche', 'Recherche'), ('favori', 'Ajout Favori')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_page', models.URLField(blank=True, null=True)),
                ('duree_engagement', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='analytics.client')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='analytics.produit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='analytics.sessionnavigation')),
            ],
            options={
                'verbose_name': 'Événement comportemental',
                'verbose_name_plural': 'Événements comportementaux',
                'db_table': 'fact_evenement_comportemental',
            },
        ),
        migrations.CreateModel(
            name='WidgetDashboard',
            fields=[
                ('id_widget', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('type_widget', models.CharField(choices=[('kpi_card', 'Carte KPI'), ('line_chart', 'Graphique ligne'), ('bar_chart', 'Graphique barres'), ('pie_chart', 'Graphique circulaire'), ('table', 'Tableau de données'), ('funnel', 'Entonnoir'), ('gauge', 'Jauge'), ('heatmap', 'Carte de chaleur')], max_length=20)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('largeur', models.IntegerField(default=6)),
                ('hauteur', models.IntegerField(default=4)),
                ('filtre_periode', models.CharField(blank=True, max_length=20)),
                ('filtre_region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dimensions', models.ManyToManyField(blank=True, to='analytics.dimensionanalyse')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.indicateurpersonnalise')),
            ],
            options={
                'verbose_name': 'Widget Dashboard',
                'verbose_name_plural': 'Widgets Dashboard',
                'db_table': 'config_widget',
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_commande'], name='fait_comman_date_co_491df6_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client', 'date_commande'], name='fait_comman_client__14650c_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['commercial', 'annee', 'mois'], name='fait_comman_commerc_9a2b79_idx'),
        ),
        migrations.AddIndex(
            model_name='donneebrute',
            index=models.Index(fields=['config', 'date_transaction'], name='donnee_brut_config__b92e90_idx'),
        ),
        migrations.AddIndex(
            model_name='donneebrute',
            index=models.Index(fields=['code_client'], name='donnee_brut_code_cl_e7c366_idx'),
        ),
        migrations.AddIndex(
            model_name='donneebrute',
            index=models.Index(fields=['code_article'], name='donnee_brut_code_ar_418998_idx'),
        ),
        migrations.AddIndex(
            model_name='evenementcomportemental',
            index=models.Index(fields=['type_evenement', 'timestamp'], name='fact_evenem_type_ev_ebbbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='evenementcomportemental',
            index=models.Index(fields=['produit', 'type_evenement'], name='fact_evenem_produit_22aa31_idx'),
        ),
        migrations.AddIndex(
            model_name='evenementcomportemental',
            index=models.Index(fields=['client', 'timestamp'], name='fact_evenem_client__d3eb6f_idx'),
        ),
    ]
